#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE)
root <- "/home/kingrider/GSE89223_download"
out <- file.path(root,"audits/G7_tximport_20261009")
Sys.setenv(R_LIBS_USER=file.path(out,"lib"))
.libPaths(c(file.path(out,"lib"),.libPaths()))
stopifnot(as.character(packageVersion("tximport"))=="1.40.0")
message("G7_START ",format(Sys.time(),"%Y-%m-%dT%H:%M:%S%z"))
stopifnot(!dir.exists(file.path(out,"result_v1")))
manifest <- read.delim("/home/kingrider/Projects/RNASeqAnalysisWithSalmon/metadata/derived/GSE89223_sample_manifest.tsv",check.names=FALSE)
pre <- readLines(file.path(root,"metadata/runs.txt"),warn=FALSE)
pre <- pre[nzchar(pre)]
stopifnot(nrow(manifest)==32L,length(pre)==32L,!anyDuplicated(manifest$run),setequal(pre,manifest$run))
manifest <- manifest[match(pre,manifest$run),,drop=FALSE]
stopifnot(identical(manifest$run,pre))
trackA <- manifest[manifest$paper_final_set=="yes",,drop=FALSE]
trackB <- manifest[manifest$paired_pca_sensitivity=="yes",,drop=FALSE]
stopifnot(nrow(trackA)==22L,table(factor(trackA$paper_group,levels=c("tumor","control")))==c(10L,12L))
stopifnot(nrow(trackB)==18L,length(unique(trackB$patient_id))==9L)
stopifnot(all(table(trackB$patient_id)==2L))
stopifnot(all(trackB$analysis_group %in% c("pca_tumor","pca_adjacent_normal")))
stopifnot(all(tapply(trackB$analysis_group,trackB$patient_id,function(x) length(unique(x)))==2L))
message("COHORT_PASS ALL=32 TRACK_A=22 TRACK_B=18")
tx <- read.delim(file.path(root,"reference/G3_GENCODEv19_GRCh37p13/derived/tx2gene.tsv"),check.names=FALSE)
stopifnot(nrow(tx)==196520L,!anyDuplicated(tx$transcript_id),!anyNA(tx$gene_id))
txmap <- tx[,c("transcript_id","gene_id")]
files <- file.path(root,"salmon/G6_SF_raw_v1",manifest$run,"quant.sf")
names(files) <- manifest$run
stopifnot(all(file.exists(files)))
first <- read.delim(files[[1]],nrows=196521L,check.names=FALSE)
stopifnot(nrow(first)==196520L)
stopifnot(setequal(first$Name,tx$transcript_id))
message("REFERENCE_IDS_PASS 196520 mapped; mismatch=0")
for(i in seq_along(files)) {
  x <- read.delim(files[[i]],check.names=FALSE)
  if(!identical(x$Name,first$Name)) stop("Transcript order/ID mismatch: ",names(files)[i])
  if(nrow(x)!=196520L || anyDuplicated(x$Name)) stop("Malformed transcript keys: ",names(files)[i])
}
message("ALL_QUANT_KEYS_PASS 32")
txi <- tximport::tximport(files,type="salmon",tx2gene=txmap,ignoreTxVersion=FALSE,countsFromAbundance="no",dropInfReps=TRUE)
stopifnot(identical(colnames(txi$counts),manifest$run))
stopifnot(identical(dim(txi$counts),dim(txi$abundance)),identical(dim(txi$counts),dim(txi$length)))
stopifnot(nrow(txi$counts)==length(unique(txmap$gene_id)))
stopifnot(all(is.finite(txi$counts)),all(is.finite(txi$abundance)),all(is.finite(txi$length)))
stopifnot(all(txi$counts>=0),all(txi$abundance>=0),all(txi$length>=0))
stopifnot(identical(rownames(txi$counts),rownames(txi$abundance)),identical(rownames(txi$counts),rownames(txi$length)))
message("TXIMPORT_PASS genes=",nrow(txi$counts)," columns=",ncol(txi$counts))
dest <- file.path(out,"result_v1")
dir.create(dest,showWarnings=FALSE)
stopifnot(dir.exists(dest))
saveRDS(txi,file.path(dest,"tximport_gene_all32_v1.rds"),compress="xz")
write.csv(txi$counts,file.path(dest,"estimated_gene_counts_all32_v1.csv"),row.names=TRUE)
write.csv(txi$abundance,file.path(dest,"gene_tpm_all32_v1.csv"),row.names=TRUE)
write.csv(txi$length,file.path(dest,"average_effective_lengths_all32_v1.csv"),row.names=TRUE)
write.csv(manifest,file.path(dest,"metadata_all32_v1.csv"),row.names=FALSE)
write.csv(trackA,file.path(dest,"trackA_22_samples_v1.csv"),row.names=FALSE)
write.csv(trackB,file.path(dest,"trackB_18_samples_v1.csv"),row.names=FALSE)
m <- data.frame(run=manifest$run,group=manifest$analysis_group,input_estimated_counts=colSums(txi$counts),gene_tpm_sum=colSums(txi$abundance),genes_with_nonzero_counts=colSums(txi$counts>0))
write.csv(m,file.path(dest,"gene_level_qc_all32_v1.csv"),row.names=FALSE)
writeLines(capture.output(sessionInfo()),file.path(dest,"sessionInfo.txt"))
message("G7_RESULT_FILES ",paste(basename(list.files(dest)),collapse=","))
message("G7_DONE ",format(Sys.time(),"%Y-%m-%dT%H:%M:%S%z"))